name: dev_deploy
on:
  push:
    branches:    
      - develop
  # pull_request:
  #   branches:
  #     - develop
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Linux Deploy
        run: bash .github/workflows/dev_deploy.sh
        env:
          DEV_PRIVATE_KEY: ${{ secrets.DEV_PRIVATE_KEY }}
          DEV_IDENTITY: ${{ secrets.DEV_IDENTITY }}
          DEV_LAUNCHPAD_CANISTERID: ${{ secrets.DEV_LAUNCHPAD_CANISTERID }}
          DEV_OWNER_PRINCIPAL: ${{ secrets.DEV_OWNER_PRINCIPAL }}
          DEV_POINT_CANISTERID: ${{ secrets.DEV_POINT_CANISTERID }}
          DEV_RECORD_CANISTERID: ${{ secrets.DEV_RECORD_CANISTERID }}
          DEV_SHIKU_CANISTERID: ${{ secrets.DEV_SHIKU_CANISTERID }}
          DEV_TEST_CANISTERID: ${{ secrets.DEV_TEST_CANISTERID }}
          DEV_TEST_PRIVATE_KEY: ${{ secrets.DEV_TEST_PRIVATE_KEY }}
      - name: creates output
        run:  sh ./sync.sh
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@devel
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: main.mo
          destination-github-username: 'Bochslertech'
          destination-repository-name: 'SERVICE_CANDID'
          user-email: xiaohuangniu
          commit-message: update candid
          target-branch: main   